image: mcr.microsoft.com/dotnet/sdk
stages:
  - build
  - test
  - publish
build:
  stage: build
  script:
    - 'dotnet restore'
    - 'dotnet build'
test:
  stage: test
  script:
    - 'dotnet test UnitTest/UnitTest.csproj'
publish:
  stage: publish
  script:
    - 'dotnet publish CustomerFramework/CustomerFramework.csproj'